//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.xerox.com/gt/100/", ClrNamespace="www.xerox.com.gt._100")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xerox.com/gt/100/", ConfigurationName="ITdmServiceDevice")]
public interface ITdmServiceDevice
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/CheckForUpdates", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/CheckForUpdatesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/CheckForUpdates", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="UpdateManifestPackage")]
    UpdateManifestType CheckForUpdates(ManifestPackageType ManifestPackage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/DescribeDevice", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/DescribeDeviceResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/DescribeDevice", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void DescribeDevice(DescribeDevicePackageType DeviceDescriptionPackage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/ReportUpdateStatus", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/ReportUpdateStatusResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/ReportUpdateStatus", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void ReportUpdateStatus(UpdateStatusPackageType UpdateStatusPackage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/ReportDeviceComponentChanges", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/ReportDeviceComponentChangesRespons" +
        "e")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/ReportDeviceComponentChanges", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void ReportDeviceComponentChanges(ComponentPackageType ComponentPackage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/RemoteCommandReply", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/RemoteCommandReplyResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/RemoteCommandReply", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void RemoteCommandReply(RemoteCommandResultType RemoteCommandResultPackage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/SendAlert", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/SendAlertResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/SendAlert", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    void SendAlert(AlertPackageType AlertPackage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.xerox.com/gt/100/ITdmServiceDevice/CheckMedia", ReplyAction="http://www.xerox.com/gt/100/ITdmServiceDevice/CheckMediaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.xerox.com.gt._100.FaultPackageType), Action="http://www.xerox.com/gt/100/ITdmServiceDevice/CheckMedia", Name="FaultPackage")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    BooleanType CheckMedia(UsedMediaType UsedMediaPackage);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class ManifestPackageType
{
    
    private string deviceGUIDField;
    
    private ManifestCategoryBaseType[] deviceManifestField;
    
    private ManifestCategoryBaseType[] targetManifestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DeviceGUID
    {
        get
        {
            return this.deviceGUIDField;
        }
        set
        {
            this.deviceGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ManifestCategory", IsNullable=false)]
    public ManifestCategoryBaseType[] DeviceManifest
    {
        get
        {
            return this.deviceManifestField;
        }
        set
        {
            this.deviceManifestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ManifestCategory", IsNullable=false)]
    public ManifestCategoryBaseType[] TargetManifest
    {
        get
        {
            return this.targetManifestField;
        }
        set
        {
            this.targetManifestField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ManifestCategoryType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class ManifestCategoryBaseType
{
    
    private string nameField;
    
    private string versionField;
    
    private System.DateTime installedDateField;
    
    private bool installedDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime InstalledDate
    {
        get
        {
            return this.installedDateField;
        }
        set
        {
            this.installedDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InstalledDateSpecified
    {
        get
        {
            return this.installedDateFieldSpecified;
        }
        set
        {
            this.installedDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class BooleanType
{
    
    private bool defaultValueField;
    
    private bool defaultValueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool DefaultValue
    {
        get
        {
            return this.defaultValueField;
        }
        set
        {
            this.defaultValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultValueSpecified
    {
        get
        {
            return this.defaultValueFieldSpecified;
        }
        set
        {
            this.defaultValueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class UsedMediaType
{
    
    private string mediaSerialNumberField;
    
    private System.DateTime mediaExpiringDateField;

    private int typeField;

    private bool typeFieldSpecified;
    
    private bool typeSpecified1Field;
    
    private string stationIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MediaSerialNumber
    {
        get
        {
            return this.mediaSerialNumberField;
        }
        set
        {
            this.mediaSerialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime MediaExpiringDate
    {
        get
        {
            return this.mediaExpiringDateField;
        }
        set
        {
            this.mediaExpiringDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)] 
    public int Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TypeSpecified
    {
        get
        {
            return this.typeFieldSpecified;
        }
        set
        {
            this.typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TypeSpecified", Order=3)]
    public bool TypeSpecified1
    {
        get
        {
            return this.typeSpecified1Field;
        }
        set
        {
            this.typeSpecified1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]    
    public string StationID
    {
        get
        {
            return this.stationIDField;
        }
        set
        {
            this.stationIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class AlertPackageType
{
    
    private string deviceGUIDField;
    
    private RemoteAlertsInstanceType remoteAlertsField;
    
    private DeviceStatusesType deviceStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DeviceGUID
    {
        get
        {
            return this.deviceGUIDField;
        }
        set
        {
            this.deviceGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public RemoteAlertsInstanceType RemoteAlerts
    {
        get
        {
            return this.remoteAlertsField;
        }
        set
        {
            this.remoteAlertsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DeviceStatusesType DeviceStatus
    {
        get
        {
            return this.deviceStatusField;
        }
        set
        {
            this.deviceStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class RemoteAlertsInstanceType
{
    
    private RemoteAlertInstanceType[] remoteAlertField;
    
    private bool isSnapShotField;
    
    private bool isSnapShotFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RemoteAlert", Order=0)]
    public RemoteAlertInstanceType[] RemoteAlert
    {
        get
        {
            return this.remoteAlertField;
        }
        set
        {
            this.remoteAlertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsSnapShot
    {
        get
        {
            return this.isSnapShotField;
        }
        set
        {
            this.isSnapShotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsSnapShotSpecified
    {
        get
        {
            return this.isSnapShotFieldSpecified;
        }
        set
        {
            this.isSnapShotFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class RemoteAlertInstanceType
{
    
    private string idField;
    
    private string componentSerialNumberField;
    
    private string componentDeviceTypeField;
    
    private bool isAlertRemovedField;
    
    private System.DateTime occurredOnField;
    
    private bool occurredOnFieldSpecified;
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ComponentSerialNumber
    {
        get
        {
            return this.componentSerialNumberField;
        }
        set
        {
            this.componentSerialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string ComponentDeviceType
    {
        get
        {
            return this.componentDeviceTypeField;
        }
        set
        {
            this.componentDeviceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public bool IsAlertRemoved
    {
        get
        {
            return this.isAlertRemovedField;
        }
        set
        {
            this.isAlertRemovedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime OccurredOn
    {
        get
        {
            return this.occurredOnField;
        }
        set
        {
            this.occurredOnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OccurredOnSpecified
    {
        get
        {
            return this.occurredOnFieldSpecified;
        }
        set
        {
            this.occurredOnFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class DeviceStatusesType
{
    
    private int statusField;
    
    private int serviceStatusField;
    
    private System.DateTime statusDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int ServiceStatus
    {
        get
        {
            return this.serviceStatusField;
        }
        set
        {
            this.serviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime StatusDate
    {
        get
        {
            return this.statusDateField;
        }
        set
        {
            this.statusDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class RemoteCommandResultType
{
    
    private string idField;
    
    private string instanceIDField;
    
    private int statusField;
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string InstanceID
    {
        get
        {
            return this.instanceIDField;
        }
        set
        {
            this.instanceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class ComponentType
{
    
    private string serialNumberField;
    
    private string typeField;
    
    private string manufacturerField;
    
    private string modelField;
    
    private string descriptionField;
    
    private string userNameField;
    
    private int actionField;
    
    private System.DateTime statusDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Manufacturer
    {
        get
        {
            return this.manufacturerField;
        }
        set
        {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Model
    {
        get
        {
            return this.modelField;
        }
        set
        {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public int Action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public System.DateTime StatusDate
    {
        get
        {
            return this.statusDateField;
        }
        set
        {
            this.statusDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class ComponentPackageType
{
    
    private string deviceGUIDField;
    
    private ComponentType[] componentsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DeviceGUID
    {
        get
        {
            return this.deviceGUIDField;
        }
        set
        {
            this.deviceGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Component", IsNullable=false)]
    public ComponentType[] Components
    {
        get
        {
            return this.componentsField;
        }
        set
        {
            this.componentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class ManifestInstallationStatusType
{
    
    private int statusField;
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class UpdateStatusPackageType
{
    
    private string deviceGUIDField;
    
    private ManifestInstallationStatusType manifestInstallationStatusField;
    
    private ManifestCategoryBaseType[] deviceManifestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DeviceGUID
    {
        get
        {
            return this.deviceGUIDField;
        }
        set
        {
            this.deviceGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ManifestInstallationStatusType ManifestInstallationStatus
    {
        get
        {
            return this.manifestInstallationStatusField;
        }
        set
        {
            this.manifestInstallationStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ManifestCategory", IsNullable=false)]
    public ManifestCategoryBaseType[] DeviceManifest
    {
        get
        {
            return this.deviceManifestField;
        }
        set
        {
            this.deviceManifestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class DeviceDescriptionType
{
    
    private string deviceGUIDField;
    
    private string logicalDeviceIDField;
    
    private string typeField;
    
    private string manufacturerField;
    
    private string modelField;
    
    private string serialNumberField;
    
    private string mACAddressField;
    
    private string hostNameField;
    
    private string iPAddressField;
    
    private string descriptionField;
    
    private string softwareVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DeviceGUID
    {
        get
        {
            return this.deviceGUIDField;
        }
        set
        {
            this.deviceGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string LogicalDeviceID
    {
        get
        {
            return this.logicalDeviceIDField;
        }
        set
        {
            this.logicalDeviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Manufacturer
    {
        get
        {
            return this.manufacturerField;
        }
        set
        {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Model
    {
        get
        {
            return this.modelField;
        }
        set
        {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string SerialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string MACAddress
    {
        get
        {
            return this.mACAddressField;
        }
        set
        {
            this.mACAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string HostName
    {
        get
        {
            return this.hostNameField;
        }
        set
        {
            this.hostNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string IPAddress
    {
        get
        {
            return this.iPAddressField;
        }
        set
        {
            this.iPAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string SoftwareVersion
    {
        get
        {
            return this.softwareVersionField;
        }
        set
        {
            this.softwareVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class DescribeDevicePackageType
{
    
    private string deviceGUIDField;
    
    private DeviceDescriptionType deviceDescriptionField;
    
    private DeviceStatusesType deviceStatusField;
    
    private RemoteAlertsInstanceType remoteAlertsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DeviceGUID
    {
        get
        {
            return this.deviceGUIDField;
        }
        set
        {
            this.deviceGUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public DeviceDescriptionType DeviceDescription
    {
        get
        {
            return this.deviceDescriptionField;
        }
        set
        {
            this.deviceDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DeviceStatusesType DeviceStatus
    {
        get
        {
            return this.deviceStatusField;
        }
        set
        {
            this.deviceStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public RemoteAlertsInstanceType RemoteAlerts
    {
        get
        {
            return this.remoteAlertsField;
        }
        set
        {
            this.remoteAlertsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class UpdateManifestType
{
    
    private ManifestCategoryType[] manifestCategoryField;
    
    private int transactionalFailureModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ManifestCategory", Order=0)]
    public ManifestCategoryType[] ManifestCategory
    {
        get
        {
            return this.manifestCategoryField;
        }
        set
        {
            this.manifestCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int TransactionalFailureMode
    {
        get
        {
            return this.transactionalFailureModeField;
        }
        set
        {
            this.transactionalFailureModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xerox.com/gt/100/")]
public partial class ManifestCategoryType : ManifestCategoryBaseType
{
    
    private int modeField;
    
    private string filePathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string FilePath
    {
        get
        {
            return this.filePathField;
        }
        set
        {
            this.filePathField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITdmServiceDeviceChannel : ITdmServiceDevice, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TdmServiceDeviceClient : System.ServiceModel.ClientBase<ITdmServiceDevice>, ITdmServiceDevice
{
    
    public TdmServiceDeviceClient()
    {
    }
    
    public TdmServiceDeviceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TdmServiceDeviceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TdmServiceDeviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TdmServiceDeviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public UpdateManifestType CheckForUpdates(ManifestPackageType ManifestPackage)
    {
        return base.Channel.CheckForUpdates(ManifestPackage);
    }
    
    public void DescribeDevice(DescribeDevicePackageType DeviceDescriptionPackage)
    {
        base.Channel.DescribeDevice(DeviceDescriptionPackage);
    }
    
    public void ReportUpdateStatus(UpdateStatusPackageType UpdateStatusPackage)
    {
        base.Channel.ReportUpdateStatus(UpdateStatusPackage);
    }
    
    public void ReportDeviceComponentChanges(ComponentPackageType ComponentPackage)
    {
        base.Channel.ReportDeviceComponentChanges(ComponentPackage);
    }
    
    public void RemoteCommandReply(RemoteCommandResultType RemoteCommandResultPackage)
    {
        base.Channel.RemoteCommandReply(RemoteCommandResultPackage);
    }
    
    public void SendAlert(AlertPackageType AlertPackage)
    {
        base.Channel.SendAlert(AlertPackage);
    }
    
    public BooleanType CheckMedia(UsedMediaType UsedMediaPackage)
    {
        return base.Channel.CheckMedia(UsedMediaPackage);
    }
}
namespace www.xerox.com.gt._100
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManifestPackageType", Namespace="http://www.xerox.com/gt/100/")]
    public partial class ManifestPackageType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DeviceGUIDField;
        
        private www.xerox.com.gt._100.ArrayOfManifestCategoryBaseType DeviceManifestField;
        
        private www.xerox.com.gt._100.ArrayOfManifestCategoryBaseType TargetManifestField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeviceGUID
        {
            get
            {
                return this.DeviceGUIDField;
            }
            set
            {
                this.DeviceGUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.xerox.com.gt._100.ArrayOfManifestCategoryBaseType DeviceManifest
        {
            get
            {
                return this.DeviceManifestField;
            }
            set
            {
                this.DeviceManifestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.xerox.com.gt._100.ArrayOfManifestCategoryBaseType TargetManifest
        {
            get
            {
                return this.TargetManifestField;
            }
            set
            {
                this.TargetManifestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfManifestCategoryBaseType", Namespace="http://www.xerox.com/gt/100/", ItemName="ManifestCategory")]
    public class ArrayOfManifestCategoryBaseType : System.Collections.Generic.List<www.xerox.com.gt._100.ManifestCategoryBaseType>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManifestCategoryBaseType", Namespace="http://www.xerox.com/gt/100/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.xerox.com.gt._100.ManifestCategoryType))]
    public partial class ManifestCategoryBaseType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string VersionField;
        
        private System.DateTime InstalledDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime InstalledDate
        {
            get
            {
                return this.InstalledDateField;
            }
            set
            {
                this.InstalledDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManifestCategoryType", Namespace="http://www.xerox.com/gt/100/")]
    public partial class ManifestCategoryType : www.xerox.com.gt._100.ManifestCategoryBaseType
    {
        
        private int ModeField;
        
        private string FilePathField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Mode
        {
            get
            {
                return this.ModeField;
            }
            set
            {
                this.ModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="FaultPackage", Namespace="http://www.xerox.com/gt/100/", IsNullable=false)]
    public partial class FaultPackageType : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("FaultPackageType", "http://www.xerox.com/gt/100/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
